import { PlaceHolderImages } from './placeholder-images';
import type { Suggestion, UserProfile } from './types';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const mockUsers: Record<string, Omit<UserProfile, 'role'>> = {
  'user-1': { uid: 'user-1', email: 'jane.doe@example.com', displayName: 'Jane Doe', photoURL: findImage('user-avatar-1') },
  'user-2': { uid: 'user-2', email: 'peter.jones@example.com', displayName: 'Peter Jones', photoURL: findImage('user-avatar-2') },
  'user-3': { uid: 'user-3', email: 'susan.smith@example.com', displayName: 'Susan Smith', photoURL: findImage('user-avatar-3') },
  'student123': { uid: 'student123', email: 'student@unilag.edu', displayName: 'John Student', photoURL: findImage('student-avatar') },
  'admin456': { uid: 'admin456', email: 'sees-admin@unilag.edu', displayName: 'Admin E. Xecutive', photoURL: findImage('admin-avatar') },
  'superadmin789': { uid: 'superadmin789', email: 'super@unilag.edu', displayName: 'Super Admin', photoURL: findImage('superadmin-avatar') },
};

export const mockSuggestions: Suggestion[] = [
  {
    suggestionId: 'a1b2c3d4',
    title: 'Implement a Campus-wide Recycling Program',
    body: 'A comprehensive recycling program should be established across all faculties and hostels. We need designated bins for plastics, paper, and glass. This will reduce waste and promote environmental consciousness among students and staff.',
    authorUid: 'user-1',
    authorDisplayName: mockUsers['user-1'].displayName!,
    authorPhotoURL: mockUsers['user-1'].photoURL,
    category: 'ENVIRONMENTAL_SUSTAINABILITY',
    status: 'SHORTLISTED',
    upvotesCount: 158,
    impactScore: 5,
    feasibilityRating: 4,
    costEffectivenessRating: 4,
    submissionTimestamp: new Date('2023-10-26T10:00:00Z'),
    commentsCount: 12,
  },
  {
    suggestionId: 'e5f6g7h8',
    title: 'Upgrade University Wi-Fi Infrastructure',
    body: 'The current Wi-Fi is unreliable, especially in lecture halls and libraries. An upgrade to Wi-Fi 6 would significantly improve connectivity for academic and research purposes. This is crucial for a modern university.',
    authorUid: 'user-2',
    authorDisplayName: mockUsers['user-2'].displayName!,
    authorPhotoURL: mockUsers['user-2'].photoURL,
    category: 'INFRASTRUCTURE_IT',
    status: 'IMPLEMENTED',
    upvotesCount: 234,
    impactScore: 5,
    feasibilityRating: 3,
    costEffectivenessRating: 3,
    submissionTimestamp: new Date('2023-09-15T14:30:00Z'),
    commentsCount: 25,
  },
  {
    suggestionId: 'i9j0k1l2',
    title: 'Introduce a Course on "AI and Society"',
    body: 'As AI becomes more prevalent, it\'s vital that engineering students understand its societal implications. A new compulsory course for final year students would cover ethics, bias, and the future of work in the age of AI.',
    authorUid: 'user-3',
    authorDisplayName: mockUsers['user-3'].displayName!,
    authorPhotoURL: mockUsers['user-3'].photoURL,
    category: 'ACADEMIC_CURRICULUM',
    status: 'UNDER_REVIEW',
    upvotesCount: 78,
    impactScore: 0,
    feasibilityRating: 0,
    costEffectivenessRating: 0,
    submissionTimestamp: new Date('2024-03-10T09:00:00Z'),
    commentsCount: 5,
  },
  {
    suggestionId: 'm3n4o5p6',
    title: 'Anonymous Feedback System for SEES Administration',
    body: 'Students often fear victimization when giving feedback. An anonymous digital portal would allow for more honest and constructive criticism of administrative processes, leading to better governance and student satisfaction.',
    authorUid: 'ANONYMOUS',
    authorDisplayName: 'Anonymous',
    authorPhotoURL: findImage('anonymous-avatar'),
    category: 'ADMINISTRATIVE_SEES',
    status: 'SUBMITTED',
    upvotesCount: 45,
    impactScore: 0,
    feasibilityRating: 0,
    costEffectivenessRating: 0,
    submissionTimestamp: new Date('2024-05-01T11:20:00Z'),
    commentsCount: 2,
  },
  {
    suggestionId: 'q7r8s9t0',
    title: 'Redesign of the Faculty of Engineering Website',
    body: 'The current website is outdated and difficult to navigate. A complete redesign focusing on mobile-first principles and modern UI/UX would better represent our faculty and provide essential information more effectively.',
    authorUid: 'user-1',
    authorDisplayName: mockUsers['user-1'].displayName!,
    authorPhotoURL: mockUsers['user-1'].photoURL,
    category: 'TECHNICAL_DESIGN',
    status: 'ARCHIVED_REJECTED',
    upvotesCount: 92,
    impactScore: 3,
    feasibilityRating: 5,
    costEffectivenessRating: 4,
    submissionTimestamp: new Date('2023-11-20T18:00:00Z'),
    commentsCount: 18,
  },
];
